Update build-and-test.yml

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -35,3 +35,23 @@ jobs:
       with:
         name: jacoco-report
         path: app/build/reports/jacoco/test
+
+  docker_build:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Verify JAR file exists
+      run: if [ -f "app/build/libs/app-0.0.1-SNAPSHOT.jar" ]; then echo "JAR file exists"; else echo "JAR file not found"; exit 1; fi
+
+    - name: Build Docker image
+      run: docker build -t your-docker-image-name:latest .
+
+    - name: Login to Docker Hub
+      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+
+    - name: Push Docker image
+      run: docker push your-docker-image-name:latest
