Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -8,51 +8,61 @@ jobs:
     environment: Dev
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up JDK
-      uses: actions/setup-java@v1
-      with:
-        java-version: '17'
+      - name: Set up JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: '17'
 
-    - name: Build with Gradle
-      run: ./gradlew build
+      - name: Build with Gradle
+        run: ./gradlew build
 
-    - name: Run tests and generate JaCoCo report
-      run: ./gradlew test jacocoTestReport
+      - name: Run tests and generate JaCoCo report
+        run: ./gradlew test jacocoTestReport
 
-    - name: Run PMD
-      run: ./gradlew pmdMain
+      - name: Run PMD
+        run: ./gradlew pmdMain
 
-    - name: Upload PMD report
-      uses: actions/upload-artifact@v4
-      with:
-        name: pmd-report
-        path: app/build/reports/pmd
+      - name: Check PMD report and fail build if violations exist
+        run: |
+          violations=$(grep -o 'violation' app/build/reports/pmd/main.html | wc -l)
+          if [ "$violations" -gt 0 ]; then
+            echo "PMD violations detected! Failing the build."
+            exit 1
+          fi
 
-    - name: Upload JaCoCo report
-      uses: actions/upload-artifact@v4
-      with:
-        name: jacoco-report
-        path: app/build/reports/jacoco/test
+      - name: Upload PMD report
+        uses: actions/upload-artifact@v4
+        with:
+          name: pmd-report
+          path: app/build/reports/pmd
 
-    # Add Docker build step
-    - name: Build Docker image
-      run: |
-        docker build -t chethancn/3pchess:${{ github.sha }} .
-    # Log in to Docker Hub
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Upload JaCoCo report
+        uses: actions/upload-artifact@v4
+        with:
+          name: jacoco-report
+          path: app/build/reports/jacoco/test
 
-    # Tag and push Docker image
-    - name: Tag Docker image
-      run: |
-        docker tag chethancn/3pchess:${{ github.sha }} chethancn/3pchess:latest
-    - name: Push Docker image
-      run: |
-        docker push chethancn/3pchess:${{ github.sha }}
-        docker push chethancn/3pchess:latest
+      # Add Docker build step
+      - name: Build Docker image
+        run: |
+          docker build -t chethancn/3pchess:${{ github.sha }} .
+
+      # Log in to Docker Hub
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      # Tag and push Docker image
+      - name: Tag Docker image
+        run: |
+          docker tag chethancn/3pchess:${{ github.sha }} chethancn/3pchess:latest
+
+      - name: Push Docker image
+        run: |
+          docker push chethancn/3pchess:${{ github.sha }}
+          docker push chethancn/3pchess:latest
